token:
  expiration_time: 86400000
  secret: '{cipher}AQCV3jV83+i/penh27+OndUYwvUDGAuYkr9QV1cBr9d51PxxZ7PFz84WndO+608RnEUwtvj1SFV6Gs58liA+wu9iWviZ3L626dPxLILOpGpl6cmChHVeJbPCvNnUTsiLzrJBoRSjikVbBbLo2eJEyy3obvVGFKMIWfJis6PDt2ZMVt5AsaRIH+ELCZgQCUb22Z5MyYUD8T1c+Lak0hV50ja9zRL4etHbHk1bLUDc5SOfIYmwaOe3ZgMdrkMWpRY5sycvNlegkLFAiFkzwID7gOvsl541CaCuYFhugYzhY180WqGYW1FXzFMPfPzmoiCMnZm1MH+i11sZZsRfB1kHXgwyHrIEqkxz7hxOgYy+JUHp04KKcFFNL55R1ApgL8m4Bfo='
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: '{cipher}AQCQnqgTt34h/JanzMc6zm/baGkpBAD6eF6mjknvnpUKHE9VI7/+uK7ZqEHrmf/waGQYivqZX58L4hTCwkQdCCFdAvMnXWNvZ7IqbDg4QDE0G3lsUVuDObdgPmszmc+KeSY2pNd6VPycOK02ismpsM+hhjofaxcTeNT38RaquXTzgRw+KrLqic7gzqwg2JGTh61yZAGHO4r0wnBJQBTfpS3pY+BiD8m26by61q/CVe2DXxM7vNSgnGRmsz8BmPZWWyGCvWrvP2EYCNdjUi6vfw/XKcKXKNAmeUMNruubc6f1dPuGigUcJiUXsG/h60lTbSABuXnFpYV2wi1sEaWFLfAvposAMB8W+aUGl3mXJ3UhuAASZrb9zD/+W1t6LUjxB2Y='
    password:
    driver-class-name: org.h2.Driver

gateway:
  ip: 175.194.246.90